"""RSS/Atom subscription source catalog for papers, news, and alerts."""
from __future__ import annotations

from typing import Any, Dict, List, Optional

RSS_SOURCES: List[Dict[str, Any]] = [
    {
        'id': 'arxiv-radiotherapy-ai',
        'name': 'arXiv 放疗 + AI',
        'short_name': 'arXiv RT+AI',
        'kind': 'academic',
        'kind_label': '预印本',
        'source': 'arXiv',
        'source_type': 'paper',
        'category': 'paper',
        'feed_url': 'https://export.arxiv.org/api/query?search_query=all:radiotherapy+AND+all:%22artificial+intelligence%22&start=0&max_results=50&sortBy=submittedDate&sortOrder=descending',
        'homepage': 'https://arxiv.org/',
        'enabled': True,
        'trust_level': 'medium',
        'collection_method': 'arXiv Atom 检索源',
        'description': 'arXiv 中 radiotherapy 与 artificial intelligence 相关的最新预印本。',
        'base_score': 70,
        'max_items_per_run': 50,
        'tags': ['arXiv', '预印本', '放疗', 'AI'],
    },
    {
        'id': 'ijrobp-red-journal',
        'name': 'International Journal of Radiation Oncology•Biology•Physics',
        'short_name': 'Red Journal',
        'kind': 'journal',
        'kind_label': '放疗期刊',
        'source': 'IJROBP',
        'source_type': 'paper',
        'category': 'paper',
        'feed_url': 'https://rss.sciencedirect.com/publication/science/03603016',
        'homepage': 'https://www.sciencedirect.com/journal/international-journal-of-radiation-oncology-biology-physics',
        'enabled': True,
        'trust_level': 'high',
        'collection_method': 'ScienceDirect RSS 订阅',
        'description': '红皮期刊 International Journal of Radiation Oncology•Biology•Physics 最新论文 RSS。',
        'base_score': 85,
        'max_items_per_run': 30,
        'tags': ['Red Journal', 'IJROBP', '放疗期刊'],
    },
    {
        'id': 'radonc-green-journal',
        'name': 'Radiotherapy and Oncology',
        'short_name': 'Green Journal',
        'kind': 'journal',
        'kind_label': '放疗期刊',
        'source': 'Radiotherapy and Oncology',
        'source_type': 'paper',
        'category': 'paper',
        'feed_url': 'https://rss.sciencedirect.com/publication/science/01678140',
        'homepage': 'https://www.sciencedirect.com/journal/radiotherapy-and-oncology',
        'enabled': True,
        'trust_level': 'high',
        'collection_method': 'ScienceDirect RSS 订阅',
        'description': '绿皮期刊 Radiotherapy and Oncology 最新论文 RSS。',
        'base_score': 85,
        'max_items_per_run': 30,
        'tags': ['Green Journal', 'Radiotherapy and Oncology', '放疗期刊'],
    },
    {
        'id': 'fda-medwatch',
        'name': 'FDA MedWatch Safety Alerts',
        'short_name': 'FDA MedWatch',
        'kind': 'regulatory',
        'kind_label': '监管/安全',
        'source': 'FDA',
        'source_type': 'news',
        'category': 'regulatory',
        'feed_url': 'https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/medwatch/rss.xml',
        'homepage': 'https://www.fda.gov/safety/medwatch-fda-safety-information-and-adverse-event-reporting-program',
        'enabled': True,
        'trust_level': 'high',
        'collection_method': 'FDA MedWatch RSS 订阅',
        'description': 'FDA MedWatch 医疗产品安全警报与召回信息 RSS。',
        'base_score': 82,
        'max_items_per_run': 20,
        'tags': ['FDA', 'MedWatch', '安全警报', '监管'],
    },
    {
        'id': 'medicalxpress-cancer',
        'name': 'Medical Xpress Oncology/Cancer',
        'short_name': 'MedXpress Cancer',
        'kind': 'industry_news',
        'kind_label': '行业媒体',
        'source': 'Medical Xpress',
        'source_type': 'news',
        'category': 'research',
        'feed_url': 'https://medicalxpress.com/rss-feed/cancer-news/',
        'homepage': 'https://medicalxpress.com/cancer-news/',
        'enabled': True,
        'trust_level': 'medium',
        'collection_method': 'Medical Xpress Cancer RSS 订阅',
        'description': 'Medical Xpress 肿瘤与癌症研究新闻 RSS。',
        'base_score': 72,
        'max_items_per_run': 20,
        'tags': ['Medical Xpress', '肿瘤新闻', '研究进展'],
    },
    {
        'id': 'medicalxpress-breaking-cancer',
        'name': 'Medical Xpress Breaking Oncology/Cancer',
        'short_name': 'MedXpress Breaking',
        'kind': 'industry_news',
        'kind_label': '行业媒体',
        'source': 'Medical Xpress',
        'source_type': 'news',
        'category': 'research',
        'feed_url': 'https://medicalxpress.com/rss-feed/breaking/cancer-news/',
        'homepage': 'https://medicalxpress.com/cancer-news/',
        'enabled': True,
        'trust_level': 'medium',
        'collection_method': 'Medical Xpress Breaking Cancer RSS 订阅',
        'description': 'Medical Xpress 肿瘤与癌症突发研究新闻 RSS。',
        'base_score': 76,
        'max_items_per_run': 20,
        'tags': ['Medical Xpress', '突发新闻', '肿瘤新闻'],
    },
    {
        'id': 'aacr-cancer-discovery',
        'name': 'AACR Cancer Discovery',
        'short_name': 'Cancer Discovery',
        'kind': 'journal',
        'kind_label': '肿瘤期刊',
        'source': 'AACR Cancer Discovery',
        'source_type': 'paper',
        'category': 'paper',
        'feed_url': 'https://aacrjournals.org/rss/site_1000003/1000004.xml',
        'homepage': 'https://aacrjournals.org/cancerdiscovery',
        'enabled': True,
        'trust_level': 'high',
        'collection_method': 'AACR 期刊 RSS 订阅',
        'description': 'AACR Cancer Discovery 最新论文 RSS。',
        'base_score': 84,
        'max_items_per_run': 30,
        'tags': ['AACR', 'Cancer Discovery', '肿瘤研究'],
    },
    {
        'id': 'aacr-clinical-cancer-research',
        'name': 'AACR Clinical Cancer Research',
        'short_name': 'Clinical Cancer Research',
        'kind': 'journal',
        'kind_label': '肿瘤期刊',
        'source': 'AACR Clinical Cancer Research',
        'source_type': 'paper',
        'category': 'paper',
        'feed_url': 'https://aacrjournals.org/rss/site_1000013/1000009.xml',
        'homepage': 'https://aacrjournals.org/clincancerres',
        'enabled': True,
        'trust_level': 'high',
        'collection_method': 'AACR 期刊 RSS 订阅',
        'description': 'AACR Clinical Cancer Research 最新论文 RSS。',
        'base_score': 84,
        'max_items_per_run': 30,
        'tags': ['AACR', 'Clinical Cancer Research', '临床转化研究'],
    },
    {
        'id': 'medlineplus-cancer',
        'name': 'MedlinePlus Cancer',
        'short_name': 'MedlinePlus Cancer',
        'kind': 'medical_reference',
        'kind_label': '医学参考',
        'source': 'MedlinePlus',
        'source_type': 'news',
        'category': 'industry_news',
        'feed_url': 'https://medlineplus.gov/feeds/topics/cancer.xml',
        'homepage': 'https://medlineplus.gov/cancer.html',
        'enabled': True,
        'trust_level': 'high',
        'collection_method': 'MedlinePlus 主题 RSS 订阅',
        'description': 'MedlinePlus 癌症主题健康信息 RSS，空 feed 视为成功。',
        'base_score': 68,
        'max_items_per_run': 20,
        'tags': ['MedlinePlus', '癌症', '医学参考'],
    },
    {
        'id': 'medlineplus-radiation-therapy',
        'name': 'MedlinePlus Radiation Therapy',
        'short_name': 'MedlinePlus RT',
        'kind': 'medical_reference',
        'kind_label': '医学参考',
        'source': 'MedlinePlus',
        'source_type': 'news',
        'category': 'industry_news',
        'feed_url': 'https://medlineplus.gov/feeds/topics/radiationtherapy.xml',
        'homepage': 'https://medlineplus.gov/radiationtherapy.html',
        'enabled': True,
        'trust_level': 'high',
        'collection_method': 'MedlinePlus 主题 RSS 订阅',
        'description': 'MedlinePlus 放射治疗主题健康信息 RSS，空 feed 视为成功。',
        'base_score': 72,
        'max_items_per_run': 20,
        'tags': ['MedlinePlus', '放射治疗', '医学参考'],
    },
]


def enabled_rss_sources() -> List[Dict[str, Any]]:
    return [dict(source) for source in RSS_SOURCES if source.get('enabled')]


def get_rss_source(source_id: str) -> Optional[Dict[str, Any]]:
    for source in RSS_SOURCES:
        if source['id'] == source_id:
            return dict(source)
    return None
